/**
 * generated by Xtext 2.25.0
 */
package de.raytracer.rtdsl.rayTracerModel;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Camera</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.raytracer.rtdsl.rayTracerModel.Camera#getName <em>Name</em>}</li>
 * </ul>
 *
 * @see de.raytracer.rtdsl.rayTracerModel.RayTracerModelPackage#getCamera()
 * @model
 * @generated
 */
public interface Camera extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see de.raytracer.rtdsl.rayTracerModel.RayTracerModelPackage#getCamera_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link de.raytracer.rtdsl.rayTracerModel.Camera#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

} // Camera
