/**
 * generated by Xtext 2.25.0
 */
package de.raytracer.rtdsl.rayTracerModel;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see de.raytracer.rtdsl.rayTracerModel.RayTracerModelFactory
 * @model kind="package"
 * @generated
 */
public interface RayTracerModelPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "rayTracerModel";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.raytracer.de/rtdsl/RayTracerModel";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "rayTracerModel";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  RayTracerModelPackage eINSTANCE = de.raytracer.rtdsl.rayTracerModel.impl.RayTracerModelPackageImpl.init();

  /**
   * The meta object id for the '{@link de.raytracer.rtdsl.rayTracerModel.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.raytracer.rtdsl.rayTracerModel.impl.ModelImpl
   * @see de.raytracer.rtdsl.rayTracerModel.impl.RayTracerModelPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__NAME = 0;

  /**
   * The feature id for the '<em><b>Element</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__ELEMENT = 1;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link de.raytracer.rtdsl.rayTracerModel.impl.BoxImpl <em>Box</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.raytracer.rtdsl.rayTracerModel.impl.BoxImpl
   * @see de.raytracer.rtdsl.rayTracerModel.impl.RayTracerModelPackageImpl#getBox()
   * @generated
   */
  int BOX = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOX__NAME = 0;

  /**
   * The number of structural features of the '<em>Box</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOX_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link de.raytracer.rtdsl.rayTracerModel.impl.SphereImpl <em>Sphere</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.raytracer.rtdsl.rayTracerModel.impl.SphereImpl
   * @see de.raytracer.rtdsl.rayTracerModel.impl.RayTracerModelPackageImpl#getSphere()
   * @generated
   */
  int SPHERE = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SPHERE__NAME = 0;

  /**
   * The number of structural features of the '<em>Sphere</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SPHERE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link de.raytracer.rtdsl.rayTracerModel.impl.CameraImpl <em>Camera</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.raytracer.rtdsl.rayTracerModel.impl.CameraImpl
   * @see de.raytracer.rtdsl.rayTracerModel.impl.RayTracerModelPackageImpl#getCamera()
   * @generated
   */
  int CAMERA = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CAMERA__NAME = 0;

  /**
   * The number of structural features of the '<em>Camera</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CAMERA_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link de.raytracer.rtdsl.rayTracerModel.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see de.raytracer.rtdsl.rayTracerModel.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the attribute '{@link de.raytracer.rtdsl.rayTracerModel.Model#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see de.raytracer.rtdsl.rayTracerModel.Model#getName()
   * @see #getModel()
   * @generated
   */
  EAttribute getModel_Name();

  /**
   * Returns the meta object for the containment reference list '{@link de.raytracer.rtdsl.rayTracerModel.Model#getElement <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Element</em>'.
   * @see de.raytracer.rtdsl.rayTracerModel.Model#getElement()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Element();

  /**
   * Returns the meta object for class '{@link de.raytracer.rtdsl.rayTracerModel.Box <em>Box</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Box</em>'.
   * @see de.raytracer.rtdsl.rayTracerModel.Box
   * @generated
   */
  EClass getBox();

  /**
   * Returns the meta object for the attribute '{@link de.raytracer.rtdsl.rayTracerModel.Box#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see de.raytracer.rtdsl.rayTracerModel.Box#getName()
   * @see #getBox()
   * @generated
   */
  EAttribute getBox_Name();

  /**
   * Returns the meta object for class '{@link de.raytracer.rtdsl.rayTracerModel.Sphere <em>Sphere</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sphere</em>'.
   * @see de.raytracer.rtdsl.rayTracerModel.Sphere
   * @generated
   */
  EClass getSphere();

  /**
   * Returns the meta object for the attribute '{@link de.raytracer.rtdsl.rayTracerModel.Sphere#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see de.raytracer.rtdsl.rayTracerModel.Sphere#getName()
   * @see #getSphere()
   * @generated
   */
  EAttribute getSphere_Name();

  /**
   * Returns the meta object for class '{@link de.raytracer.rtdsl.rayTracerModel.Camera <em>Camera</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Camera</em>'.
   * @see de.raytracer.rtdsl.rayTracerModel.Camera
   * @generated
   */
  EClass getCamera();

  /**
   * Returns the meta object for the attribute '{@link de.raytracer.rtdsl.rayTracerModel.Camera#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see de.raytracer.rtdsl.rayTracerModel.Camera#getName()
   * @see #getCamera()
   * @generated
   */
  EAttribute getCamera_Name();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  RayTracerModelFactory getRayTracerModelFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link de.raytracer.rtdsl.rayTracerModel.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.raytracer.rtdsl.rayTracerModel.impl.ModelImpl
     * @see de.raytracer.rtdsl.rayTracerModel.impl.RayTracerModelPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MODEL__NAME = eINSTANCE.getModel_Name();

    /**
     * The meta object literal for the '<em><b>Element</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__ELEMENT = eINSTANCE.getModel_Element();

    /**
     * The meta object literal for the '{@link de.raytracer.rtdsl.rayTracerModel.impl.BoxImpl <em>Box</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.raytracer.rtdsl.rayTracerModel.impl.BoxImpl
     * @see de.raytracer.rtdsl.rayTracerModel.impl.RayTracerModelPackageImpl#getBox()
     * @generated
     */
    EClass BOX = eINSTANCE.getBox();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BOX__NAME = eINSTANCE.getBox_Name();

    /**
     * The meta object literal for the '{@link de.raytracer.rtdsl.rayTracerModel.impl.SphereImpl <em>Sphere</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.raytracer.rtdsl.rayTracerModel.impl.SphereImpl
     * @see de.raytracer.rtdsl.rayTracerModel.impl.RayTracerModelPackageImpl#getSphere()
     * @generated
     */
    EClass SPHERE = eINSTANCE.getSphere();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SPHERE__NAME = eINSTANCE.getSphere_Name();

    /**
     * The meta object literal for the '{@link de.raytracer.rtdsl.rayTracerModel.impl.CameraImpl <em>Camera</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.raytracer.rtdsl.rayTracerModel.impl.CameraImpl
     * @see de.raytracer.rtdsl.rayTracerModel.impl.RayTracerModelPackageImpl#getCamera()
     * @generated
     */
    EClass CAMERA = eINSTANCE.getCamera();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CAMERA__NAME = eINSTANCE.getCamera_Name();

  }

} //RayTracerModelPackage
