/*
 * generated by Xtext 2.25.0
 */
package de.raytracer.rtdsl.ui;

import com.google.inject.Injector;
import de.raytracer.rtdsl.ui.internal.RtdslActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class RayTracerModelExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(RtdslActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		RtdslActivator activator = RtdslActivator.getInstance();
		return activator != null ? activator.getInjector(RtdslActivator.DE_RAYTRACER_RTDSL_RAYTRACERMODEL) : null;
	}

}
