/*
 * generated by Xtext 2.25.0
 */
package de.raytracer.rtdsl.parser.antlr;

import com.google.inject.Inject;
import de.raytracer.rtdsl.parser.antlr.internal.InternalRayTracerModelParser;
import de.raytracer.rtdsl.services.RayTracerModelGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class RayTracerModelParser extends AbstractAntlrParser {

	@Inject
	private RayTracerModelGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalRayTracerModelParser createParser(XtextTokenStream stream) {
		return new InternalRayTracerModelParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public RayTracerModelGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(RayTracerModelGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
