/*
 * generated by Xtext 2.25.0
 */
package de.raytracer.rtdsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class RayTracerModelAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("de/raytracer/rtdsl/parser/antlr/internal/InternalRayTracerModel.tokens");
	}
}
