/*
 * generated by Xtext 2.25.0
 */
package de.raytracer.rtdsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class RayTracerModelUiModule extends AbstractRayTracerModelUiModule {

	public RayTracerModelUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
