/*
 * generated by Xtext 2.25.0
 */
package de.raytracer.rtdsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import de.raytracer.rtdsl.RayTracerModelRuntimeModule;
import de.raytracer.rtdsl.RayTracerModelStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class RayTracerModelIdeSetup extends RayTracerModelStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new RayTracerModelRuntimeModule(), new RayTracerModelIdeModule()));
	}
	
}
