/*
 * generated by Xtext 2.25.0
 */
package de.raytracer.rtdsl.ide;


/**
 * Use this class to register ide components.
 */
public class RayTracerModelIdeModule extends AbstractRayTracerModelIdeModule {
}
