/*
 * generated by Xtext 2.25.0
 */
package de.raytracer.rtdsl.ui.tests;

import com.google.inject.Injector;
import de.raytracer.rtdsl.ui.internal.RtdslActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class RayTracerModelUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return RtdslActivator.getInstance().getInjector("de.raytracer.rtdsl.RayTracerModel");
	}

}
