/*
 * generated by Xtext 2.25.0
 */
package de.raytracer.rtdsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractRayTracerModelScopeProvider extends DelegatingScopeProvider {
}
