/*
 * generated by Xtext 2.25.0
 */
package de.raytracer.rtdsl.serializer;

import com.google.inject.Inject;
import de.raytracer.rtdsl.rayTracerModel.Box;
import de.raytracer.rtdsl.rayTracerModel.Camera;
import de.raytracer.rtdsl.rayTracerModel.Model;
import de.raytracer.rtdsl.rayTracerModel.RayTracerModelPackage;
import de.raytracer.rtdsl.rayTracerModel.Sphere;
import de.raytracer.rtdsl.services.RayTracerModelGrammarAccess;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;

@SuppressWarnings("all")
public class RayTracerModelSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private RayTracerModelGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == RayTracerModelPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case RayTracerModelPackage.BOX:
				sequence_Box(context, (Box) semanticObject); 
				return; 
			case RayTracerModelPackage.CAMERA:
				sequence_Camera(context, (Camera) semanticObject); 
				return; 
			case RayTracerModelPackage.MODEL:
				sequence_Model(context, (Model) semanticObject); 
				return; 
			case RayTracerModelPackage.SPHERE:
				sequence_Sphere(context, (Sphere) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     Box returns Box
	 *
	 * Constraint:
	 *     name=ID
	 */
	protected void sequence_Box(ISerializationContext context, Box semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, RayTracerModelPackage.Literals.BOX__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, RayTracerModelPackage.Literals.BOX__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getBoxAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Camera returns Camera
	 *
	 * Constraint:
	 *     name=ID
	 */
	protected void sequence_Camera(ISerializationContext context, Camera semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, RayTracerModelPackage.Literals.CAMERA__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, RayTracerModelPackage.Literals.CAMERA__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getCameraAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Model returns Model
	 *
	 * Constraint:
	 *     (name=ID (element+=Box | element+=Sphere | element+=Camera)*)
	 */
	protected void sequence_Model(ISerializationContext context, Model semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Sphere returns Sphere
	 *
	 * Constraint:
	 *     name=ID
	 */
	protected void sequence_Sphere(ISerializationContext context, Sphere semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, RayTracerModelPackage.Literals.SPHERE__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, RayTracerModelPackage.Literals.SPHERE__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getSphereAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
}
