/*
 * generated by Xtext 2.25.0
 */
package de.raytracer.rtdsl.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractRayTracerModelValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(de.raytracer.rtdsl.rayTracerModel.RayTracerModelPackage.eINSTANCE);
		return result;
	}
}
