/*
 * generated by Xtext 2.25.0
 */
package de.raytracer.rtdsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class RayTracerModelStandaloneSetup extends RayTracerModelStandaloneSetupGenerated {

	public static void doSetup() {
		new RayTracerModelStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
