/*
 * generated by Xtext 2.25.0
 */
package de.raytracer.rtdsl;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class RayTracerModelRuntimeModule extends AbstractRayTracerModelRuntimeModule {
}
